/**
 * Rich realistic data for NER-SHIELD Dashboard
 * Aligned with Northeast disaster management and logistics scenarios.
 */

export const mockDashboardMetrics = {
  districtsMonitored: 8,
  totalDistricts: 8,
  roadsTotal: 19,
  roadsOpen: 15,
  roadsDisrupted: 3,
  roadsRestricted: 1,
  activeIncidents: 4,
  vehiclesInTransit: 4,
  vehiclesDelayed: 2,
  highRiskCorridors: 3,
  delayedDeliveries: 2,
  populationImpactedEstimate: '420,000',
  averageDelayHours: 3.8,
  activeClearanceOperations: 2,
  lastUpdated: new Date().toISOString(),
};

export const mockAlerts = [
  {
    id: 'ALT-101',
    severity: 'Critical',
    category: 'BLOCKED_ROAD',
    title: 'NH-6 Dima Hasao Corridor Blocked',
    location: 'Dima Hasao Pass (Km 142), NH-6',
    state: 'Assam / Meghalaya Border',
    time: '25 mins ago',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    description: 'Major debris avalanche spanning 180 meters. Both lanes impassable for heavy freight vehicles.',
    impact: 'Cuts off direct road transit between Guwahati and Barak Valley / Tripura / Mizoram.',
    recommendedAction: 'Mandatory diversion via NH-27 Nagaon-Dimapur bypass. Halt non-essential freight at Jatinga checkpost.',
    affectedCommodities: ['MEDICINE', 'FOOD', 'FUEL'],
    clearanceStatus: 'Clearance in progress (Est. 24-36 hrs)',
  },
  {
    id: 'ALT-102',
    severity: 'High',
    category: 'FLOOD',
    title: 'Flash Flood Inundation on NH-37 Stretch',
    location: 'Barak Valley stretch near Silchar',
    state: 'Assam',
    time: '1 hour ago',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    description: 'Water levels reaching 0.6m above carriageway due to continuous heavy monsoon precipitation.',
    impact: 'Submerged road shoulder; low-clearance vehicles cannot pass.',
    recommendedAction: 'Restrict transit to heavy 6-axle relief trucks only. Escort medical supply convoys via SDRF watercraft if necessary.',
    affectedCommodities: ['PERISHABLE_AGRI', 'GENERAL_FREIGHT'],
    clearanceStatus: 'Water receded by 10cm; pump trucks deployed',
  },
  {
    id: 'ALT-103',
    severity: 'High',
    category: 'DELAYED_DELIVERY',
    title: 'Critical Insulin & Vaccine Shipment Delayed',
    location: 'En route near Nongpoh, NH-6',
    state: 'Meghalaya',
    time: '40 mins ago',
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
    description: 'Vehicle TRK-NER-101 carrying cold-chain vaccines has exceeded planned arrival buffer by 2.5 hours.',
    impact: 'Temperature-controlled storage battery life at 65%. Delivery to Imphal Depot compromised.',
    recommendedAction: 'Issue priority transit clearance tag; redirect vehicle through Lumding-Kohima alternate route.',
    affectedCommodities: ['MEDICINE'],
    clearanceStatus: 'Rerouting active',
  },
  {
    id: 'ALT-104',
    severity: 'Moderate',
    category: 'HEAVY_RAINFALL',
    title: 'Heavy Precipitation & Dense Fog Hazard',
    location: 'Umiam Lake - Nongpoh Hill Corridor',
    state: 'Meghalaya',
    time: '2 hours ago',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    description: 'Visibility below 15 meters on steep gradients. Rainfall rate 45mm/hr.',
    impact: 'Average fleet transit speed reduced to 25 km/h.',
    recommendedAction: 'Activate warning beacons; enforce 30m following distance on NH-6 descending turns.',
    affectedCommodities: ['GENERAL'],
    clearanceStatus: 'Advisory active',
  },
  {
    id: 'ALT-105',
    severity: 'Moderate',
    category: 'HIGH_RISK_ROUTE',
    title: 'Slope Instability Warning on NH-29 Kohima',
    location: 'Kohima Bypass Bridge Section, NH-29',
    state: 'Nagaland',
    time: '3 hours ago',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
    description: 'Soil saturation index at 89%. Micro-slips detected on embankment.',
    impact: 'Single-lane alternating traffic flow.',
    recommendedAction: 'Weight restriction capped at 16 Metric Tonnes per axle. Standby earthmovers on site.',
    affectedCommodities: ['CONSTRUCTION', 'FOOD'],
    clearanceStatus: 'Monitored by Border Roads Org (BRO)',
  },
];

export const mockDistrictConnectivity = [
  {
    id: 'dist-kamrup',
    name: 'Kamrup Metropolitan (Guwahati)',
    state: 'Assam',
    status: 'FULL_ACCESS',
    accessibilityScore: 98,
    isolated: false,
    activeCorridors: 4,
    blockedCorridors: 0,
    criticalSupplyBufferDays: 14,
    keyHub: 'Central Northeast Logistics Gateway',
    vulnerability: 'LOW',
  },
  {
    id: 'dist-east-khasi',
    name: 'East Khasi Hills (Shillong)',
    state: 'Meghalaya',
    status: 'RESTRICTED',
    accessibilityScore: 72,
    isolated: false,
    activeCorridors: 2,
    blockedCorridors: 1,
    criticalSupplyBufferDays: 6,
    keyHub: 'NH-6 Gateway to Southern NER',
    vulnerability: 'MODERATE',
  },
  {
    id: 'dist-dima-hasao',
    name: 'Dima Hasao (Haflong)',
    state: 'Assam',
    status: 'ISOLATED',
    accessibilityScore: 28,
    isolated: true,
    activeCorridors: 0,
    blockedCorridors: 2,
    criticalSupplyBufferDays: 2.5,
    keyHub: 'Critical Rail & Road Chokepoint',
    vulnerability: 'CRITICAL',
  },
  {
    id: 'dist-cachar',
    name: 'Cachar (Silchar)',
    state: 'Assam',
    status: 'CRITICAL_BOTTLENECK',
    accessibilityScore: 45,
    isolated: false,
    activeCorridors: 1,
    blockedCorridors: 1,
    criticalSupplyBufferDays: 4,
    keyHub: 'Barak Valley Distribution Hub',
    vulnerability: 'HIGH',
  },
  {
    id: 'dist-kohima',
    name: 'Kohima',
    state: 'Nagaland',
    status: 'RESTRICTED',
    accessibilityScore: 68,
    isolated: false,
    activeCorridors: 2,
    blockedCorridors: 0,
    criticalSupplyBufferDays: 7,
    keyHub: 'Nagaland Highway Confluence',
    vulnerability: 'MODERATE',
  },
  {
    id: 'dist-imphal-west',
    name: 'Imphal West',
    state: 'Manipur',
    status: 'CRITICAL_BOTTLENECK',
    accessibilityScore: 52,
    isolated: false,
    activeCorridors: 1,
    blockedCorridors: 1,
    criticalSupplyBufferDays: 3.5,
    keyHub: 'Manipur Supply Depot',
    vulnerability: 'HIGH',
  },
  {
    id: 'dist-papum-pare',
    name: 'Papum Pare (Itanagar)',
    state: 'Arunachal Pradesh',
    status: 'FULL_ACCESS',
    accessibilityScore: 88,
    isolated: false,
    activeCorridors: 3,
    blockedCorridors: 0,
    criticalSupplyBufferDays: 10,
    keyHub: 'Western Arunachal Access Hub',
    vulnerability: 'LOW',
  },
  {
    id: 'dist-west-tripura',
    name: 'West Tripura (Agartala)',
    state: 'Tripura',
    status: 'RESTRICTED',
    accessibilityScore: 60,
    isolated: false,
    activeCorridors: 1,
    blockedCorridors: 1,
    criticalSupplyBufferDays: 5,
    keyHub: 'Tripura State Hub',
    vulnerability: 'HIGH',
  },
];

export const mockRouteRecommendations = {
  source: 'Guwahati Logistics Hub (Kamrup)',
  destination: 'Imphal Valley Depot (Manipur)',
  commodity: 'MEDICINE',
  priorityLabel: 'Critical Medical Supplies (Vaccines/Insulin)',
  recommended: {
    id: 'ROUTE-ALTERNATE',
    name: 'Route B (AI-Optimized Bypass via NH-27 & Dimapur)',
    path: 'Guwahati → Nagaon (NH-27) → Lumding Bypass → Dimapur (NH-29) → Kohima → Imphal',
    distanceKm: 530,
    eta: '12h 00m',
    etaHours: 12.0,
    riskLevel: 'LOW',
    riskScore: 0.14,
    status: 'OPEN & CLEAR',
    reason: 'Avoids severe landslide hazard and road blockage on NH-6 Dima Hasao pass. Safe grade roads with active BRO patrols.',
    costBreakdown: {
      roadQuality: 'Good to Excellent (4-lane NH-27 section)',
      hazardProbability: '4% (Low rainfall forecast)',
      fuelEfficiencyFactor: 'Optimal cruising speed 55 km/h',
    },
    waypoints: [
      { name: 'Guwahati Hub', lat: 26.1798, lng: 91.7519, status: 'Clear' },
      { name: 'Nagaon Confluence', lat: 26.3453, lng: 92.6841, status: 'Clear' },
      { name: 'Lumding Bypass', lat: 26.2135, lng: 93.0573, status: 'Clear' },
      { name: 'Dimapur Entry', lat: 25.899, lng: 93.7263, status: 'Clear' },
      { name: 'Kohima Checkpoint', lat: 25.6742, lng: 94.1085, status: 'Cautious (Fog)' },
      { name: 'Imphal Depot', lat: 24.817, lng: 93.9363, status: 'Clear' },
    ],
  },
  primary: {
    id: 'ROUTE-PRIMARY',
    name: 'Route A (Direct NH-6 via Shillong & Haflong)',
    path: 'Guwahati → Shillong (NH-6) → Jowai → Dima Hasao Pass → Silchar → Imphal',
    distanceKm: 485,
    eta: '14h 30m (Delayed / Impassable)',
    etaHours: 14.5,
    riskLevel: 'HIGH',
    riskScore: 0.88,
    status: 'BLOCKED AT DIMA HASAO',
    reason: 'Total physical road blockage due to major landslide at Km 142. Heavy rainfall ongoing with high risk of additional secondary landslides.',
    costBreakdown: {
      roadQuality: 'Severely Damaged at pass segment',
      hazardProbability: '88% (Flash flood & landslide warning)',
      fuelEfficiencyFactor: 'Zero movement at bottleneck',
    },
  },
  aiInsight: 'System chosen Route B despite +45 km distance because risk penalty for MEDICINE is multiplied by 3.5x. This guarantees 100% arrival probability with a net 2.5 hours saved over blocked direct route.',
};

export const mockVehicles = [
  {
    id: 'TRK-NER-101',
    registration: 'AS-01-GC-4482',
    type: 'Heavy Freight Truck (16T)',
    driverName: 'Ramesh Kumar',
    driverContact: '+91 98765-43210',
    cargo: 'Essential Medical Supplies (Insulin/Cold Chain)',
    commodity: 'MEDICINE',
    origin: 'Guwahati Central Depot',
    destination: 'Imphal Valley Hospital Hub',
    status: 'Delayed - Rerouting',
    statusCategory: 'DELAYED',
    speedKmH: 48,
    heading: 'East-Southeast',
    lastSignal: '2 mins ago',
    lat: 26.12,
    lng: 92.20,
    assignedRoute: 'ROUTE-ALTERNATE',
    fuelLevel: '78%',
    temperatureSensor: '3.4°C (Normal)',
  },
  {
    id: 'TRK-NER-204',
    registration: 'ML-05-D-8199',
    type: 'Refrigerated Cargo Van',
    driverName: 'Bijen Singh',
    driverContact: '+91 98621-99881',
    cargo: 'Perishable Agri Produce (Organic Ginger & Spices)',
    commodity: 'AGRICULTURAL',
    origin: 'Shillong Agri Market',
    destination: 'Guwahati Air Cargo',
    status: 'Caution - Fog Slowed',
    statusCategory: 'CAUTION',
    speedKmH: 35,
    heading: 'North',
    lastSignal: '1 min ago',
    lat: 25.80,
    lng: 91.87,
    assignedRoute: 'NH-6 Northbound',
    fuelLevel: '62%',
    temperatureSensor: '7.8°C (Normal)',
  },
  {
    id: 'EMG-NER-05',
    registration: 'AS-01-EA-1008',
    type: 'Disaster Relief Convoy Vehicle',
    driverName: 'Tashi Bhutia',
    driverContact: '+91 94350-11223',
    cargo: 'Emergency Relief Kits & Water Purifiers',
    commodity: 'FOOD',
    origin: 'Guwahati State Logistics Hub',
    destination: 'Haflong Relief Camp',
    status: 'Priority Escort',
    statusCategory: 'IN_TRANSIT',
    speedKmH: 62,
    heading: 'East',
    lastSignal: 'Just now',
    lat: 26.25,
    lng: 92.55,
    assignedRoute: 'NH-27 Rapid Response',
    fuelLevel: '91%',
    temperatureSensor: 'N/A',
  },
  {
    id: 'TRK-NER-309',
    registration: 'TR-01-B-5521',
    type: 'POL Fuel Tanker (20,000L)',
    driverName: 'Sunil Debbarma',
    driverContact: '+91 97740-44332',
    cargo: 'High-Octane Petrol & Diesel',
    commodity: 'GENERAL',
    origin: 'Guwahati IOCL Refinery',
    destination: 'Agartala Central Station',
    status: 'In Transit',
    statusCategory: 'IN_TRANSIT',
    speedKmH: 52,
    heading: 'South-Southwest',
    lastSignal: '4 mins ago',
    lat: 24.15,
    lng: 91.50,
    assignedRoute: 'NH-8 Southern Link',
    fuelLevel: '85%',
    temperatureSensor: 'Ambient',
  },
];

export const mockIncidents = [
  {
    id: 'INC-001',
    title: 'Major Landslide on NH-6',
    type: 'Landslide',
    severity: 'Critical',
    location: 'Dima Hasao Pass (Km 142)',
    district: 'Dima Hasao',
    state: 'Assam',
    impact: 'Road completely blocked in both directions. 180m debris mass.',
    estimatedClearance: '24 - 36 Hours',
    reportedTime: 'Today, 08:30 IST',
    verifiedBy: 'Field Patrol Team 3 (BRO / NDRF)',
    coordinates: [92.85, 25.28],
    activeResponse: '2 JCB Excavators, 1 Hydraulic Crane deployed',
    status: 'ACTIVE_BLOCKAGE',
  },
  {
    id: 'INC-002',
    title: 'Flash Flood Submergence',
    type: 'Flood',
    severity: 'High',
    location: 'Barak Valley stretch near Silchar',
    district: 'Cachar',
    state: 'Assam',
    impact: 'Water level 0.6m above road surface. Carriageway edge invisible.',
    estimatedClearance: '12 Hours',
    reportedTime: 'Today, 06:15 IST',
    verifiedBy: 'District Disaster Management Authority (DDMA)',
    coordinates: [92.75, 24.85],
    activeResponse: 'SDRF patrol boats guiding high-clearance military convoys',
    status: 'RESTRICTED_ACCESS',
  },
  {
    id: 'INC-003',
    title: 'Dense Fog & Visibility Hazard',
    type: 'Weather',
    severity: 'Moderate',
    location: 'Umiam Lake stretch, Nongpoh',
    district: 'Ri-Bhoi',
    state: 'Meghalaya',
    impact: 'Visibility below 15 meters on sharp hillside curves.',
    estimatedClearance: '4 Hours',
    reportedTime: 'Today, 10:00 IST',
    verifiedBy: 'Automated Weather Station (AWS-Nongpoh)',
    coordinates: [91.88, 25.75],
    activeResponse: 'Warning flashers and pilot escort vehicles engaged',
    status: 'CAUTION_ADVISORY',
  },
  {
    id: 'INC-004',
    title: 'Bridge Structural Repair Work',
    type: 'Roadwork',
    severity: 'Moderate',
    location: 'NH-29 Kohima Bypass Bridge',
    district: 'Kohima',
    state: 'Nagaland',
    impact: 'Single-lane alternating bottleneck for vehicles over 12T.',
    estimatedClearance: '48 Hours',
    reportedTime: 'Yesterday, 14:00 IST',
    verifiedBy: 'National Highways & Infrastructure Dev Corp (NHIDCL)',
    coordinates: [94.10, 25.65],
    activeResponse: 'Steel girder reinforcement in progress',
    status: 'SINGLE_LANE_OPEN',
  },
];
